<?php
/**
 * Données initiales des services
 * Extrait du fichier AIServiceGenerator.tsx
 */

// Services par langue et type de projet
$services = [
    // Services FR
    [
        'name_fr' => 'Nom de domaine .fr',
        'name_en' => 'Domain name .fr',
        'name_de' => 'Domainname .fr',
        'name_es' => 'Nombre de dominio .fr',
        'name_it' => 'Nome dominio .fr',
        'description_fr' => 'Réservation et configuration du nom de domaine .fr pour 1 an',
        'description_en' => 'Registration and configuration of .fr domain name for 1 year',
        'description_de' => 'Reservierung und Konfiguration des .fr Domainnamens für 1 Jahr',
        'description_es' => 'Reserva y configuración del nombre de dominio .fr por 1 año',
        'description_it' => 'Registrazione e configurazione del nome dominio .fr per 1 anno',
        'price' => 12,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Hébergement Web',
        'name_en' => 'Web Hosting',
        'name_de' => 'Web-Hosting',
        'name_es' => 'Alojamiento Web',
        'name_it' => 'Hosting Web',
        'description_fr' => 'Hébergement mutualisé avec SSL, 1 an',
        'description_en' => 'Shared hosting with SSL, 1 year',
        'description_de' => 'Shared Hosting mit SSL, 1 Jahr',
        'description_es' => 'Alojamiento compartido con SSL, 1 año',
        'description_it' => 'Hosting condiviso con SSL, 1 anno',
        'price' => 60,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Site Web One Page',
        'name_en' => 'One Page Website',
        'name_de' => 'One-Page-Website',
        'name_es' => 'Sitio Web de Una Página',
        'name_it' => 'Sito Web One Page',
        'description_fr' => 'Site moderne sur une seule page avec design responsive et animations',
        'description_en' => 'Modern single-page website with responsive design and animations',
        'description_de' => 'Moderne einseitige Website mit responsivem Design und Animationen',
        'description_es' => 'Sitio web moderno de una sola página con diseño responsive y animaciones',
        'description_it' => 'Sito web moderno a pagina singola con design responsive e animazioni',
        'price' => 200,
        'category' => 'Développement',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Design Premium',
        'name_en' => 'Premium Design',
        'name_de' => 'Premium-Design',
        'name_es' => 'Diseño Premium',
        'name_it' => 'Design Premium',
        'description_fr' => 'Design graphique haut de gamme avec identité visuelle complète',
        'description_en' => 'High-end graphic design with complete visual identity',
        'description_de' => 'Hochwertiges Grafikdesign mit vollständiger visueller Identität',
        'description_es' => 'Diseño gráfico de alta gama con identidad visual completa',
        'description_it' => 'Design grafico di alta gamma con identità visiva completa',
        'price' => 700,
        'category' => 'Design',
        'is_recommended' => 1
    ],
    [
        'name_fr' => 'SEO One Page',
        'name_en' => 'One Page SEO',
        'name_de' => 'One-Page-SEO',
        'name_es' => 'SEO Una Página',
        'name_it' => 'SEO One Page',
        'description_fr' => 'Optimisation SEO complète pour site one page avec suivi mensuel',
        'description_en' => 'Complete SEO optimization for one-page site with monthly tracking',
        'description_de' => 'Vollständige SEO-Optimierung für One-Page-Site mit monatlichem Tracking',
        'description_es' => 'Optimización SEO completa para sitio de una página con seguimiento mensual',
        'description_it' => 'Ottimizzazione SEO completa per sito one page con monitoraggio mensile',
        'price' => 600,
        'category' => 'Marketing',
        'is_recommended' => 1
    ],
    [
        'name_fr' => 'Hébergement Premium',
        'name_en' => 'Premium Hosting',
        'name_de' => 'Premium-Hosting',
        'name_es' => 'Alojamiento Premium',
        'name_it' => 'Hosting Premium',
        'description_fr' => 'Hébergement professionnel 100GB SSD, certificat SSL inclus, 1 an',
        'description_en' => 'Professional hosting 100GB SSD, SSL certificate included, 1 year',
        'description_de' => 'Professionelles Hosting 100GB SSD, SSL-Zertifikat inklusive, 1 Jahr',
        'description_es' => 'Alojamiento profesional 100GB SSD, certificado SSL incluido, 1 año',
        'description_it' => 'Hosting professionale 100GB SSD, certificato SSL incluso, 1 anno',
        'price' => 120,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Site Web Vitrine',
        'name_en' => 'Showcase Website',
        'name_de' => 'Showcase-Website',
        'name_es' => 'Sitio Web Corporativo',
        'name_it' => 'Sito Web Vetrina',
        'description_fr' => 'Site vitrine professionnel 5-8 pages avec CMS et optimisation SEO',
        'description_en' => 'Professional showcase website 5-8 pages with CMS and SEO optimization',
        'description_de' => 'Professionelle Showcase-Website 5-8 Seiten mit CMS und SEO-Optimierung',
        'description_es' => 'Sitio web corporativo profesional 5-8 páginas con CMS y optimización SEO',
        'description_it' => 'Sito web vetrina professionale 5-8 pagine con CMS e ottimizzazione SEO',
        'price' => 1800,
        'category' => 'Développement',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'SEO 1 Keyword + Backlinks',
        'name_en' => 'SEO 1 Keyword + Backlinks',
        'name_de' => 'SEO 1 Keyword + Backlinks',
        'name_es' => 'SEO 1 Palabra Clave + Backlinks',
        'name_it' => 'SEO 1 Keyword + Backlinks',
        'description_fr' => 'Positionnement sur 1 mot-clé avec création de backlinks de qualité',
        'description_en' => 'Positioning on 1 keyword with quality backlink creation',
        'description_de' => 'Positionierung auf 1 Keyword mit Erstellung hochwertiger Backlinks',
        'description_es' => 'Posicionamiento en 1 palabra clave con creación de backlinks de calidad',
        'description_it' => 'Posizionamento su 1 parola chiave con creazione backlink di qualità',
        'price' => 350,
        'category' => 'Marketing',
        'is_recommended' => 1
    ],
    [
        'name_fr' => 'Nom de domaine .com',
        'name_en' => 'Domain name .com',
        'name_de' => 'Domainname .com',
        'name_es' => 'Nombre de dominio .com',
        'name_it' => 'Nome dominio .com',
        'description_fr' => 'Réservation et configuration du nom de domaine .com pour 1 an',
        'description_en' => 'Registration and configuration of .com domain name for 1 year',
        'description_de' => 'Reservierung und Konfiguration des .com Domainnamens für 1 Jahr',
        'description_es' => 'Reserva y configuración del nombre de dominio .com por 1 año',
        'description_it' => 'Registrazione e configurazione del nome dominio .com per 1 anno',
        'price' => 18,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Hébergement E-commerce',
        'name_en' => 'E-commerce Hosting',
        'name_de' => 'E-Commerce-Hosting',
        'name_es' => 'Alojamiento E-commerce',
        'name_it' => 'Hosting E-commerce',
        'description_fr' => 'Hébergement dédié virtuel, 200GB SSD, SSL premium, 1 an',
        'description_en' => 'Virtual dedicated hosting, 200GB SSD, premium SSL, 1 year',
        'description_de' => 'Virtuelles dediziertes Hosting, 200GB SSD, Premium-SSL, 1 Jahr',
        'description_es' => 'Alojamiento dedicado virtual, 200GB SSD, SSL premium, 1 año',
        'description_it' => 'Hosting dedicato virtuale, 200GB SSD, SSL premium, 1 anno',
        'price' => 300,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Site Web E-commerce',
        'name_en' => 'E-commerce Website',
        'name_de' => 'E-Commerce-Website',
        'name_es' => 'Sitio Web E-commerce',
        'name_it' => 'Sito Web E-commerce',
        'description_fr' => 'Boutique en ligne complète avec paiement sécurisé et gestion des stocks',
        'description_en' => 'Complete online store with secure payment and inventory management',
        'description_de' => 'Kompletter Online-Shop mit sicherer Zahlung und Lagerverwaltung',
        'description_es' => 'Tienda en línea completa con pago seguro y gestión de inventario',
        'description_it' => 'Negozio online completo con pagamento sicuro e gestione inventario',
        'price' => 2300,
        'category' => 'Développement',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Passerelle de paiement',
        'name_en' => 'Payment Gateway',
        'name_de' => 'Zahlungs-Gateway',
        'name_es' => 'Pasarela de Pago',
        'name_it' => 'Gateway di Pagamento',
        'description_fr' => 'Intégration Stripe/PayPal, configuration sécurisée',
        'description_en' => 'Stripe/PayPal integration, secure configuration',
        'description_de' => 'Stripe/PayPal-Integration, sichere Konfiguration',
        'description_es' => 'Integración Stripe/PayPal, configuración segura',
        'description_it' => 'Integrazione Stripe/PayPal, configurazione sicura',
        'price' => 400,
        'category' => 'Développement',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Nom de domaine Premium',
        'name_en' => 'Premium Domain Name',
        'name_de' => 'Premium-Domainname',
        'name_es' => 'Nombre de Dominio Premium',
        'name_it' => 'Nome Dominio Premium',
        'description_fr' => 'Réservation nom de domaine premium avec protection WHOIS',
        'description_en' => 'Premium domain name reservation with WHOIS protection',
        'description_de' => 'Reservierung von Premium-Domainnamen mit WHOIS-Schutz',
        'description_es' => 'Reserva de nombre de dominio premium con protección WHOIS',
        'description_it' => 'Registrazione nome dominio premium con protezione WHOIS',
        'price' => 35,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Hébergement Dédié',
        'name_en' => 'Dedicated Hosting',
        'name_de' => 'Dediziertes Hosting',
        'name_es' => 'Alojamiento Dedicado',
        'name_it' => 'Hosting Dedicato',
        'description_fr' => 'Serveur dédié virtuel, 500GB SSD, monitoring 24/7, 1 an',
        'description_en' => 'Virtual dedicated server, 500GB SSD, 24/7 monitoring, 1 year',
        'description_de' => 'Virtueller dedizierter Server, 500GB SSD, 24/7-Überwachung, 1 Jahr',
        'description_es' => 'Servidor dedicado virtual, 500GB SSD, monitoreo 24/7, 1 año',
        'description_it' => 'Server dedicato virtuale, 500GB SSD, monitoraggio 24/7, 1 anno',
        'price' => 600,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Plateforme Sur Mesure',
        'name_en' => 'Custom Platform',
        'name_de' => 'Maßgeschneiderte Plattform',
        'name_es' => 'Plataforma Personalizada',
        'name_it' => 'Piattaforma Su Misura',
        'description_fr' => 'Application web personnalisée selon vos besoins spécifiques',
        'description_en' => 'Custom web application according to your specific needs',
        'description_de' => 'Maßgeschneiderte Webanwendung nach Ihren spezifischen Bedürfnissen',
        'description_es' => 'Aplicación web personalizada según sus necesidades específicas',
        'description_it' => 'Applicazione web personalizzata secondo le vostre esigenze specifiche',
        'price' => 3500,
        'category' => 'Développement',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Infrastructure Cloud',
        'name_en' => 'Cloud Infrastructure',
        'name_de' => 'Cloud-Infrastruktur',
        'name_es' => 'Infraestructura Cloud',
        'name_it' => 'Infrastruttura Cloud',
        'description_fr' => 'Serveurs cloud scalables avec load balancer et CDN',
        'description_en' => 'Scalable cloud servers with load balancer and CDN',
        'description_de' => 'Skalierbare Cloud-Server mit Load Balancer und CDN',
        'description_es' => 'Servidores cloud escalables con balanceador de carga y CDN',
        'description_it' => 'Server cloud scalabili con load balancer e CDN',
        'price' => 800,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Solution SaaS',
        'name_en' => 'SaaS Solution',
        'name_de' => 'SaaS-Lösung',
        'name_es' => 'Solución SaaS',
        'name_it' => 'Soluzione SaaS',
        'description_fr' => 'Plateforme SaaS complète avec abonnements et tableau de bord',
        'description_en' => 'Complete SaaS platform with subscriptions and dashboard',
        'description_de' => 'Komplette SaaS-Plattform mit Abonnements und Dashboard',
        'description_es' => 'Plataforma SaaS completa con suscripciones y panel de control',
        'description_it' => 'Piattaforma SaaS completa con abbonamenti e dashboard',
        'price' => 5500,
        'category' => 'Développement',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'API et Intégrations',
        'name_en' => 'API and Integrations',
        'name_de' => 'API und Integrationen',
        'name_es' => 'API e Integraciones',
        'name_it' => 'API e Integrazioni',
        'description_fr' => 'Développement API REST et intégrations tierces',
        'description_en' => 'REST API development and third-party integrations',
        'description_de' => 'REST-API-Entwicklung und Drittanbieter-Integrationen',
        'description_es' => 'Desarrollo API REST e integraciones de terceros',
        'description_it' => 'Sviluppo API REST e integrazioni terze parti',
        'price' => 2000,
        'category' => 'Développement',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Hébergement Business',
        'name_en' => 'Business Hosting',
        'name_de' => 'Business-Hosting',
        'name_es' => 'Alojamiento Business',
        'name_it' => 'Hosting Business',
        'description_fr' => 'Hébergement haute performance, 250GB SSD, backup quotidien, 1 an',
        'description_en' => 'High-performance hosting, 250GB SSD, daily backup, 1 year',
        'description_de' => 'Hochleistungs-Hosting, 250GB SSD, tägliches Backup, 1 Jahr',
        'description_es' => 'Alojamiento de alto rendimiento, 250GB SSD, backup diario, 1 año',
        'description_it' => 'Hosting ad alte prestazioni, 250GB SSD, backup giornaliero, 1 anno',
        'price' => 250,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Site de Location',
        'name_en' => 'Rental Website',
        'name_de' => 'Vermietungs-Website',
        'name_es' => 'Sitio Web de Alquiler',
        'name_it' => 'Sito Web di Noleggio',
        'description_fr' => 'Plateforme de location avec réservations et paiements en ligne',
        'description_en' => 'Rental platform with reservations and online payments',
        'description_de' => 'Vermietungsplattform mit Reservierungen und Online-Zahlungen',
        'description_es' => 'Plataforma de alquiler con reservas y pagos en línea',
        'description_it' => 'Piattaforma di noleggio con prenotazioni e pagamenti online',
        'price' => 3500,
        'category' => 'Développement',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Hébergement Salon',
        'name_en' => 'Salon Hosting',
        'name_de' => 'Salon-Hosting',
        'name_es' => 'Alojamiento Salón',
        'name_it' => 'Hosting Salone',
        'description_fr' => 'Hébergement optimisé avec réservations, 150GB SSD, 1 an',
        'description_en' => 'Optimized hosting with reservations, 150GB SSD, 1 year',
        'description_de' => 'Optimiertes Hosting mit Reservierungen, 150GB SSD, 1 Jahr',
        'description_es' => 'Alojamiento optimizado con reservas, 150GB SSD, 1 año',
        'description_it' => 'Hosting ottimizzato con prenotazioni, 150GB SSD, 1 anno',
        'price' => 180,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Site Web Coiffure',
        'name_en' => 'Hair Salon Website',
        'name_de' => 'Friseursalon-Website',
        'name_es' => 'Sitio Web de Peluquería',
        'name_it' => 'Sito Web Parrucchiere',
        'description_fr' => 'Site spécialisé coiffure avec prise de rendez-vous et galerie',
        'description_en' => 'Specialized hair salon website with appointment booking and gallery',
        'description_de' => 'Spezialisierte Friseursalon-Website mit Terminbuchung und Galerie',
        'description_es' => 'Sitio web especializado en peluquería con reserva de citas y galería',
        'description_it' => 'Sito web specializzato parrucchiere con prenotazione appuntamenti e galleria',
        'price' => 2500,
        'category' => 'Développement',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Shooting Photo Salon',
        'name_en' => 'Salon Photo Shoot',
        'name_de' => 'Salon-Fotoshooting',
        'name_es' => 'Sesión de Fotos Salón',
        'name_it' => 'Shooting Foto Salone',
        'description_fr' => 'Séance photo professionnelle du salon et des réalisations',
        'description_en' => 'Professional photo session of the salon and achievements',
        'description_de' => 'Professionelles Fotoshooting des Salons und der Arbeiten',
        'description_es' => 'Sesión de fotos profesional del salón y los trabajos',
        'description_it' => 'Sessione fotografica professionale del salone e delle realizzazioni',
        'price' => 400,
        'category' => 'Design',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Hébergement Artisan',
        'name_en' => 'Craftsman Hosting',
        'name_de' => 'Handwerker-Hosting',
        'name_es' => 'Alojamiento Artesano',
        'name_it' => 'Hosting Artigiano',
        'description_fr' => 'Hébergement avec galerie photos optimisée, 150GB SSD, 1 an',
        'description_en' => 'Hosting with optimized photo gallery, 150GB SSD, 1 year',
        'description_de' => 'Hosting mit optimierter Fotogalerie, 150GB SSD, 1 Jahr',
        'description_es' => 'Alojamiento con galería de fotos optimizada, 150GB SSD, 1 año',
        'description_it' => 'Hosting con galleria foto ottimizzata, 150GB SSD, 1 anno',
        'price' => 150,
        'category' => 'Infrastructure',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Site Web Artisan',
        'name_en' => 'Craftsman Website',
        'name_de' => 'Handwerker-Website',
        'name_es' => 'Sitio Web de Artesano',
        'name_it' => 'Sito Web Artigiano',
        'description_fr' => 'Site professionnel artisan avec portfolio et demande de devis',
        'description_en' => 'Professional craftsman website with portfolio and quote requests',
        'description_de' => 'Professionelle Handwerker-Website mit Portfolio und Angebotsanfragen',
        'description_es' => 'Sitio web profesional de artesano con portfolio y solicitudes de presupuesto',
        'description_it' => 'Sito web professionale artigiano con portfolio e richieste preventivo',
        'price' => 2500,
        'category' => 'Développement',
        'is_recommended' => 0
    ],
    [
        'name_fr' => 'Shooting Photo Réalisations',
        'name_en' => 'Product Photo Shoot',
        'name_de' => 'Produkt-Fotoshooting',
        'name_es' => 'Sesión de Fotos Productos',
        'name_it' => 'Shooting Foto Realizzazioni',
        'description_fr' => 'Séance photo professionnelle de vos réalisations',
        'description_en' => 'Professional photo session of your achievements',
        'description_de' => 'Professionelles Fotoshooting Ihrer Arbeiten',
        'description_es' => 'Sesión de fotos profesional de sus trabajos',
        'description_it' => 'Sessione fotografica professionale delle vostre realizzazioni',
        'price' => 500,
        'category' => 'Design',
        'is_recommended' => 0
    ]
];

// Insérer les services
$stmt = $pdo->prepare("
    INSERT INTO services (name_fr, name_en, name_de, name_es, name_it, description_fr, description_en, description_de, description_es, description_it, price, category, is_recommended, created_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())
");

foreach ($services as $service) {
    $stmt->execute([
        $service['name_fr'],
        $service['name_en'],
        $service['name_de'],
        $service['name_es'],
        $service['name_it'],
        $service['description_fr'],
        $service['description_en'],
        $service['description_de'],
        $service['description_es'],
        $service['description_it'],
        $service['price'],
        $service['category'],
        $service['is_recommended']
    ]);
}
